/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CustomerInput = IDL.Record({
  'name' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const CustomerId = IDL.Nat;
export const Timestamp = IDL.Int;
export const CustomerView = IDL.Record({
  'id' : CustomerId,
  'balance' : IDL.Int,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const DeliveryInput = IDL.Record({
  'deliveryDate' : Timestamp,
  'pricePerCan' : IDL.Nat,
  'quantity' : IDL.Nat,
  'customerId' : CustomerId,
});
export const DeliveryId = IDL.Nat;
export const DeliveryStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'delivered' : IDL.Null,
});
export const DeliveryView = IDL.Record({
  'id' : DeliveryId,
  'status' : DeliveryStatus,
  'createdAt' : Timestamp,
  'deliveryDate' : Timestamp,
  'pricePerCan' : IDL.Nat,
  'totalAmount' : IDL.Nat,
  'quantity' : IDL.Nat,
  'customerId' : CustomerId,
});
export const PaymentMethod = IDL.Variant({
  'cash' : IDL.Null,
  'online' : IDL.Null,
});
export const PaymentInput = IDL.Record({
  'method' : PaymentMethod,
  'note' : IDL.Text,
  'paymentDate' : Timestamp,
  'customerId' : CustomerId,
  'amount' : IDL.Nat,
});
export const PaymentId = IDL.Nat;
export const Payment = IDL.Record({
  'id' : PaymentId,
  'method' : PaymentMethod,
  'note' : IDL.Text,
  'createdAt' : Timestamp,
  'paymentDate' : Timestamp,
  'customerId' : CustomerId,
  'amount' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const DashboardStats = IDL.Record({
  'totalOutstandingBalance' : IDL.Int,
  'totalRevenue' : IDL.Nat,
  'totalCustomers' : IDL.Nat,
  'totalDeliveries' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addCustomer' : IDL.Func([CustomerInput], [CustomerView], []),
  'addDelivery' : IDL.Func([DeliveryInput], [DeliveryView], []),
  'addPayment' : IDL.Func([PaymentInput], [Payment], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteCustomer' : IDL.Func([CustomerId], [IDL.Bool], []),
  'deleteDelivery' : IDL.Func([DeliveryId], [IDL.Bool], []),
  'deletePayment' : IDL.Func([PaymentId], [IDL.Bool], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomer' : IDL.Func([CustomerId], [IDL.Opt(CustomerView)], ['query']),
  'getCustomerHistory' : IDL.Func(
      [CustomerId],
      [
        IDL.Record({
          'deliveries' : IDL.Vec(DeliveryView),
          'payments' : IDL.Vec(Payment),
        }),
      ],
      ['query'],
    ),
  'getDashboard' : IDL.Func(
      [],
      [
        IDL.Record({
          'stats' : DashboardStats,
          'customersWithOutstandingBalance' : IDL.Vec(CustomerView),
        }),
      ],
      ['query'],
    ),
  'getDelivery' : IDL.Func([DeliveryId], [IDL.Opt(DeliveryView)], ['query']),
  'getPayment' : IDL.Func([PaymentId], [IDL.Opt(Payment)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listCustomers' : IDL.Func([], [IDL.Vec(CustomerView)], ['query']),
  'listCustomersWithOutstandingBalance' : IDL.Func(
      [],
      [IDL.Vec(CustomerView)],
      ['query'],
    ),
  'listDeliveries' : IDL.Func([], [IDL.Vec(DeliveryView)], ['query']),
  'listDeliveriesForCustomer' : IDL.Func(
      [CustomerId],
      [IDL.Vec(DeliveryView)],
      ['query'],
    ),
  'listPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
  'listPaymentsForCustomer' : IDL.Func(
      [CustomerId],
      [IDL.Vec(Payment)],
      ['query'],
    ),
  'updateCustomer' : IDL.Func(
      [CustomerId, CustomerInput],
      [IDL.Opt(CustomerView)],
      [],
    ),
  'updateDelivery' : IDL.Func(
      [DeliveryId, DeliveryInput],
      [IDL.Opt(DeliveryView)],
      [],
    ),
  'updateDeliveryStatus' : IDL.Func(
      [DeliveryId, DeliveryStatus],
      [IDL.Opt(DeliveryView)],
      [],
    ),
  'updatePayment' : IDL.Func([PaymentId, PaymentInput], [IDL.Opt(Payment)], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CustomerInput = IDL.Record({
    'name' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const CustomerId = IDL.Nat;
  const Timestamp = IDL.Int;
  const CustomerView = IDL.Record({
    'id' : CustomerId,
    'balance' : IDL.Int,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const DeliveryInput = IDL.Record({
    'deliveryDate' : Timestamp,
    'pricePerCan' : IDL.Nat,
    'quantity' : IDL.Nat,
    'customerId' : CustomerId,
  });
  const DeliveryId = IDL.Nat;
  const DeliveryStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'delivered' : IDL.Null,
  });
  const DeliveryView = IDL.Record({
    'id' : DeliveryId,
    'status' : DeliveryStatus,
    'createdAt' : Timestamp,
    'deliveryDate' : Timestamp,
    'pricePerCan' : IDL.Nat,
    'totalAmount' : IDL.Nat,
    'quantity' : IDL.Nat,
    'customerId' : CustomerId,
  });
  const PaymentMethod = IDL.Variant({ 'cash' : IDL.Null, 'online' : IDL.Null });
  const PaymentInput = IDL.Record({
    'method' : PaymentMethod,
    'note' : IDL.Text,
    'paymentDate' : Timestamp,
    'customerId' : CustomerId,
    'amount' : IDL.Nat,
  });
  const PaymentId = IDL.Nat;
  const Payment = IDL.Record({
    'id' : PaymentId,
    'method' : PaymentMethod,
    'note' : IDL.Text,
    'createdAt' : Timestamp,
    'paymentDate' : Timestamp,
    'customerId' : CustomerId,
    'amount' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const DashboardStats = IDL.Record({
    'totalOutstandingBalance' : IDL.Int,
    'totalRevenue' : IDL.Nat,
    'totalCustomers' : IDL.Nat,
    'totalDeliveries' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addCustomer' : IDL.Func([CustomerInput], [CustomerView], []),
    'addDelivery' : IDL.Func([DeliveryInput], [DeliveryView], []),
    'addPayment' : IDL.Func([PaymentInput], [Payment], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteCustomer' : IDL.Func([CustomerId], [IDL.Bool], []),
    'deleteDelivery' : IDL.Func([DeliveryId], [IDL.Bool], []),
    'deletePayment' : IDL.Func([PaymentId], [IDL.Bool], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomer' : IDL.Func([CustomerId], [IDL.Opt(CustomerView)], ['query']),
    'getCustomerHistory' : IDL.Func(
        [CustomerId],
        [
          IDL.Record({
            'deliveries' : IDL.Vec(DeliveryView),
            'payments' : IDL.Vec(Payment),
          }),
        ],
        ['query'],
      ),
    'getDashboard' : IDL.Func(
        [],
        [
          IDL.Record({
            'stats' : DashboardStats,
            'customersWithOutstandingBalance' : IDL.Vec(CustomerView),
          }),
        ],
        ['query'],
      ),
    'getDelivery' : IDL.Func([DeliveryId], [IDL.Opt(DeliveryView)], ['query']),
    'getPayment' : IDL.Func([PaymentId], [IDL.Opt(Payment)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listCustomers' : IDL.Func([], [IDL.Vec(CustomerView)], ['query']),
    'listCustomersWithOutstandingBalance' : IDL.Func(
        [],
        [IDL.Vec(CustomerView)],
        ['query'],
      ),
    'listDeliveries' : IDL.Func([], [IDL.Vec(DeliveryView)], ['query']),
    'listDeliveriesForCustomer' : IDL.Func(
        [CustomerId],
        [IDL.Vec(DeliveryView)],
        ['query'],
      ),
    'listPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
    'listPaymentsForCustomer' : IDL.Func(
        [CustomerId],
        [IDL.Vec(Payment)],
        ['query'],
      ),
    'updateCustomer' : IDL.Func(
        [CustomerId, CustomerInput],
        [IDL.Opt(CustomerView)],
        [],
      ),
    'updateDelivery' : IDL.Func(
        [DeliveryId, DeliveryInput],
        [IDL.Opt(DeliveryView)],
        [],
      ),
    'updateDeliveryStatus' : IDL.Func(
        [DeliveryId, DeliveryStatus],
        [IDL.Opt(DeliveryView)],
        [],
      ),
    'updatePayment' : IDL.Func(
        [PaymentId, PaymentInput],
        [IDL.Opt(Payment)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };