/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type CustomerId = bigint;
export interface CustomerInput {
  'name' : string,
  'address' : string,
  'phone' : string,
}
export interface CustomerView {
  'id' : CustomerId,
  'balance' : bigint,
  'name' : string,
  'createdAt' : Timestamp,
  'address' : string,
  'phone' : string,
}
export interface DashboardStats {
  'totalOutstandingBalance' : bigint,
  'totalRevenue' : bigint,
  'totalCustomers' : bigint,
  'totalDeliveries' : bigint,
}
export type DeliveryId = bigint;
export interface DeliveryInput {
  'deliveryDate' : Timestamp,
  'pricePerCan' : bigint,
  'quantity' : bigint,
  'customerId' : CustomerId,
}
export type DeliveryStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'delivered' : null };
export interface DeliveryView {
  'id' : DeliveryId,
  'status' : DeliveryStatus,
  'createdAt' : Timestamp,
  'deliveryDate' : Timestamp,
  'pricePerCan' : bigint,
  'totalAmount' : bigint,
  'quantity' : bigint,
  'customerId' : CustomerId,
}
export interface Payment {
  'id' : PaymentId,
  'method' : PaymentMethod,
  'note' : string,
  'createdAt' : Timestamp,
  'paymentDate' : Timestamp,
  'customerId' : CustomerId,
  'amount' : bigint,
}
export type PaymentId = bigint;
export interface PaymentInput {
  'method' : PaymentMethod,
  'note' : string,
  'paymentDate' : Timestamp,
  'customerId' : CustomerId,
  'amount' : bigint,
}
export type PaymentMethod = { 'cash' : null } |
  { 'online' : null };
export type Timestamp = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addCustomer' : ActorMethod<[CustomerInput], CustomerView>,
  'addDelivery' : ActorMethod<[DeliveryInput], DeliveryView>,
  'addPayment' : ActorMethod<[PaymentInput], Payment>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteCustomer' : ActorMethod<[CustomerId], boolean>,
  'deleteDelivery' : ActorMethod<[DeliveryId], boolean>,
  'deletePayment' : ActorMethod<[PaymentId], boolean>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomer' : ActorMethod<[CustomerId], [] | [CustomerView]>,
  'getCustomerHistory' : ActorMethod<
    [CustomerId],
    { 'deliveries' : Array<DeliveryView>, 'payments' : Array<Payment> }
  >,
  'getDashboard' : ActorMethod<
    [],
    {
      'stats' : DashboardStats,
      'customersWithOutstandingBalance' : Array<CustomerView>,
    }
  >,
  'getDelivery' : ActorMethod<[DeliveryId], [] | [DeliveryView]>,
  'getPayment' : ActorMethod<[PaymentId], [] | [Payment]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listCustomers' : ActorMethod<[], Array<CustomerView>>,
  'listCustomersWithOutstandingBalance' : ActorMethod<[], Array<CustomerView>>,
  'listDeliveries' : ActorMethod<[], Array<DeliveryView>>,
  'listDeliveriesForCustomer' : ActorMethod<[CustomerId], Array<DeliveryView>>,
  'listPayments' : ActorMethod<[], Array<Payment>>,
  'listPaymentsForCustomer' : ActorMethod<[CustomerId], Array<Payment>>,
  'updateCustomer' : ActorMethod<
    [CustomerId, CustomerInput],
    [] | [CustomerView]
  >,
  'updateDelivery' : ActorMethod<
    [DeliveryId, DeliveryInput],
    [] | [DeliveryView]
  >,
  'updateDeliveryStatus' : ActorMethod<
    [DeliveryId, DeliveryStatus],
    [] | [DeliveryView]
  >,
  'updatePayment' : ActorMethod<[PaymentId, PaymentInput], [] | [Payment]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];