/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface DeliveryInput {
    deliveryDate: Timestamp;
    pricePerCan: bigint;
    quantity: bigint;
    customerId: CustomerId;
}
export type Timestamp = bigint;
export type DeliveryId = bigint;
export interface Payment {
    id: PaymentId;
    method: PaymentMethod;
    note: string;
    createdAt: Timestamp;
    paymentDate: Timestamp;
    customerId: CustomerId;
    amount: bigint;
}
export interface DashboardStats {
    totalOutstandingBalance: bigint;
    totalRevenue: bigint;
    totalCustomers: bigint;
    totalDeliveries: bigint;
}
export interface CustomerInput {
    name: string;
    address: string;
    phone: string;
}
export type PaymentId = bigint;
export type CustomerId = bigint;
export interface PaymentInput {
    method: PaymentMethod;
    note: string;
    paymentDate: Timestamp;
    customerId: CustomerId;
    amount: bigint;
}
export interface DeliveryView {
    id: DeliveryId;
    status: DeliveryStatus;
    createdAt: Timestamp;
    deliveryDate: Timestamp;
    pricePerCan: bigint;
    totalAmount: bigint;
    quantity: bigint;
    customerId: CustomerId;
}
export interface CustomerView {
    id: CustomerId;
    balance: bigint;
    name: string;
    createdAt: Timestamp;
    address: string;
    phone: string;
}
export enum DeliveryStatus {
    cancelled = "cancelled",
    pending = "pending",
    delivered = "delivered"
}
export enum PaymentMethod {
    cash = "cash",
    online = "online"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    addCustomer(input: CustomerInput): Promise<CustomerView>;
    addDelivery(input: DeliveryInput): Promise<DeliveryView>;
    addPayment(input: PaymentInput): Promise<Payment>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteCustomer(id: CustomerId): Promise<boolean>;
    deleteDelivery(id: DeliveryId): Promise<boolean>;
    deletePayment(id: PaymentId): Promise<boolean>;
    getCallerUserRole(): Promise<UserRole>;
    getCustomer(id: CustomerId): Promise<CustomerView | null>;
    getCustomerHistory(customerId: CustomerId): Promise<{
        deliveries: Array<DeliveryView>;
        payments: Array<Payment>;
    }>;
    getDashboard(): Promise<{
        stats: DashboardStats;
        customersWithOutstandingBalance: Array<CustomerView>;
    }>;
    getDelivery(id: DeliveryId): Promise<DeliveryView | null>;
    getPayment(id: PaymentId): Promise<Payment | null>;
    isCallerAdmin(): Promise<boolean>;
    listCustomers(): Promise<Array<CustomerView>>;
    listCustomersWithOutstandingBalance(): Promise<Array<CustomerView>>;
    listDeliveries(): Promise<Array<DeliveryView>>;
    listDeliveriesForCustomer(customerId: CustomerId): Promise<Array<DeliveryView>>;
    listPayments(): Promise<Array<Payment>>;
    listPaymentsForCustomer(customerId: CustomerId): Promise<Array<Payment>>;
    updateCustomer(id: CustomerId, input: CustomerInput): Promise<CustomerView | null>;
    updateDelivery(id: DeliveryId, input: DeliveryInput): Promise<DeliveryView | null>;
    updateDeliveryStatus(id: DeliveryId, status: DeliveryStatus): Promise<DeliveryView | null>;
    updatePayment(id: PaymentId, input: PaymentInput): Promise<Payment | null>;
}
import type { CustomerId as _CustomerId, CustomerView as _CustomerView, DeliveryId as _DeliveryId, DeliveryStatus as _DeliveryStatus, DeliveryView as _DeliveryView, Payment as _Payment, PaymentId as _PaymentId, PaymentInput as _PaymentInput, PaymentMethod as _PaymentMethod, Timestamp as _Timestamp, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async addCustomer(arg0: CustomerInput): Promise<CustomerView> {
        if (this.processError) {
            try {
                const result = await this.actor.addCustomer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCustomer(arg0);
            return result;
        }
    }
    async addDelivery(arg0: DeliveryInput): Promise<DeliveryView> {
        if (this.processError) {
            try {
                const result = await this.actor.addDelivery(arg0);
                return from_candid_DeliveryView_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDelivery(arg0);
            return from_candid_DeliveryView_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async addPayment(arg0: PaymentInput): Promise<Payment> {
        if (this.processError) {
            try {
                const result = await this.actor.addPayment(to_candid_PaymentInput_n5(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Payment_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPayment(to_candid_PaymentInput_n5(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Payment_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n13(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n13(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteCustomer(arg0: CustomerId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCustomer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCustomer(arg0);
            return result;
        }
    }
    async deleteDelivery(arg0: DeliveryId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDelivery(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDelivery(arg0);
            return result;
        }
    }
    async deletePayment(arg0: PaymentId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePayment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePayment(arg0);
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomer(arg0: CustomerId): Promise<CustomerView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomer(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomer(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomerHistory(arg0: CustomerId): Promise<{
        deliveries: Array<DeliveryView>;
        payments: Array<Payment>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomerHistory(arg0);
                return from_candid_record_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomerHistory(arg0);
            return from_candid_record_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboard(): Promise<{
        stats: DashboardStats;
        customersWithOutstandingBalance: Array<CustomerView>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboard();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboard();
            return result;
        }
    }
    async getDelivery(arg0: DeliveryId): Promise<DeliveryView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDelivery(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDelivery(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPayment(arg0: PaymentId): Promise<Payment | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPayment(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPayment(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listCustomers(): Promise<Array<CustomerView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCustomers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCustomers();
            return result;
        }
    }
    async listCustomersWithOutstandingBalance(): Promise<Array<CustomerView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCustomersWithOutstandingBalance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCustomersWithOutstandingBalance();
            return result;
        }
    }
    async listDeliveries(): Promise<Array<DeliveryView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listDeliveries();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listDeliveries();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async listDeliveriesForCustomer(arg0: CustomerId): Promise<Array<DeliveryView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listDeliveriesForCustomer(arg0);
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listDeliveriesForCustomer(arg0);
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async listPayments(): Promise<Array<Payment>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPayments();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPayments();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async listPaymentsForCustomer(arg0: CustomerId): Promise<Array<Payment>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPaymentsForCustomer(arg0);
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPaymentsForCustomer(arg0);
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateCustomer(arg0: CustomerId, arg1: CustomerInput): Promise<CustomerView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCustomer(arg0, arg1);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCustomer(arg0, arg1);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateDelivery(arg0: DeliveryId, arg1: DeliveryInput): Promise<DeliveryView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDelivery(arg0, arg1);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDelivery(arg0, arg1);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateDeliveryStatus(arg0: DeliveryId, arg1: DeliveryStatus): Promise<DeliveryView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDeliveryStatus(arg0, to_candid_DeliveryStatus_n23(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDeliveryStatus(arg0, to_candid_DeliveryStatus_n23(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async updatePayment(arg0: PaymentId, arg1: PaymentInput): Promise<Payment | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePayment(arg0, to_candid_PaymentInput_n5(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePayment(arg0, to_candid_PaymentInput_n5(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_DeliveryStatus_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DeliveryStatus): DeliveryStatus {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_DeliveryView_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DeliveryView): DeliveryView {
    return from_candid_record_n2(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentMethod_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMethod): PaymentMethod {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Payment_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Payment): Payment {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CustomerView]): CustomerView | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DeliveryView]): DeliveryView | null {
    return value.length === 0 ? null : from_candid_DeliveryView_n1(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Payment]): Payment | null {
    return value.length === 0 ? null : from_candid_Payment_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _PaymentId;
    method: _PaymentMethod;
    note: string;
    createdAt: _Timestamp;
    paymentDate: _Timestamp;
    customerId: _CustomerId;
    amount: bigint;
}): {
    id: PaymentId;
    method: PaymentMethod;
    note: string;
    createdAt: Timestamp;
    paymentDate: Timestamp;
    customerId: CustomerId;
    amount: bigint;
} {
    return {
        id: value.id,
        method: from_candid_PaymentMethod_n11(_uploadFile, _downloadFile, value.method),
        note: value.note,
        createdAt: value.createdAt,
        paymentDate: value.paymentDate,
        customerId: value.customerId,
        amount: value.amount
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    deliveries: Array<_DeliveryView>;
    payments: Array<_Payment>;
}): {
    deliveries: Array<DeliveryView>;
    payments: Array<Payment>;
} {
    return {
        deliveries: from_candid_vec_n19(_uploadFile, _downloadFile, value.deliveries),
        payments: from_candid_vec_n20(_uploadFile, _downloadFile, value.payments)
    };
}
function from_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _DeliveryId;
    status: _DeliveryStatus;
    createdAt: _Timestamp;
    deliveryDate: _Timestamp;
    pricePerCan: bigint;
    totalAmount: bigint;
    quantity: bigint;
    customerId: _CustomerId;
}): {
    id: DeliveryId;
    status: DeliveryStatus;
    createdAt: Timestamp;
    deliveryDate: Timestamp;
    pricePerCan: bigint;
    totalAmount: bigint;
    quantity: bigint;
    customerId: CustomerId;
} {
    return {
        id: value.id,
        status: from_candid_DeliveryStatus_n3(_uploadFile, _downloadFile, value.status),
        createdAt: value.createdAt,
        deliveryDate: value.deliveryDate,
        pricePerCan: value.pricePerCan,
        totalAmount: value.totalAmount,
        quantity: value.quantity,
        customerId: value.customerId
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cash: null;
} | {
    online: null;
}): PaymentMethod {
    return "cash" in value ? PaymentMethod.cash : "online" in value ? PaymentMethod.online : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    delivered: null;
}): DeliveryStatus {
    return "cancelled" in value ? DeliveryStatus.cancelled : "pending" in value ? DeliveryStatus.pending : "delivered" in value ? DeliveryStatus.delivered : value;
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DeliveryView>): Array<DeliveryView> {
    return value.map((x)=>from_candid_DeliveryView_n1(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Payment>): Array<Payment> {
    return value.map((x)=>from_candid_Payment_n9(_uploadFile, _downloadFile, x));
}
function to_candid_DeliveryStatus_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DeliveryStatus): _DeliveryStatus {
    return to_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentInput_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentInput): _PaymentInput {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentMethod_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): _PaymentMethod {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    method: PaymentMethod;
    note: string;
    paymentDate: Timestamp;
    customerId: CustomerId;
    amount: bigint;
}): {
    method: _PaymentMethod;
    note: string;
    paymentDate: _Timestamp;
    customerId: _CustomerId;
    amount: bigint;
} {
    return {
        method: to_candid_PaymentMethod_n7(_uploadFile, _downloadFile, value.method),
        note: value.note,
        paymentDate: value.paymentDate,
        customerId: value.customerId,
        amount: value.amount
    };
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DeliveryStatus): {
    cancelled: null;
} | {
    pending: null;
} | {
    delivered: null;
} {
    return value == DeliveryStatus.cancelled ? {
        cancelled: null
    } : value == DeliveryStatus.pending ? {
        pending: null
    } : value == DeliveryStatus.delivered ? {
        delivered: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): {
    cash: null;
} | {
    online: null;
} {
    return value == PaymentMethod.cash ? {
        cash: null
    } : value == PaymentMethod.online ? {
        online: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
